[project]
name = "matplotlib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nodar", email = "nodar.m/cybx.io" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
matplotlib = "matplotlib:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
